// create chats
export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILURE = "CREATE_CHAT_FAILURE";

// get chats
export const GET_CHATS_REQUEST = "GET_CHATS_REQUEST";
export const GET_CHATS_SUCCESS = "GET_CHATS_SUCCESS";
export const GET_CHATS_FAILURE = "GET_CHATS_FAILURE";

// get chat
export const GET_CHAT_REQUEST = "GET_CHAT_REQUEST";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAILURE = "GET_CHAT_FAILURE";

// update chat
export const UPDATE_CHAT_REQUEST = "UPDATE_CHAT_REQUEST";
export const UPDATE_CHAT_SUCCESS = "UPDATE_CHAT_SUCCESS";
export const UPDATE_CHAT_FAILURE = "UPDATE_CHAT_FAILURE";
export const UPDATE_CHAT_CLEAR = "UPDATE_CHAT_CLEAR";
