export const POST_LOADING = "POST_LOADING";

// create a new post
export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";

// get posts
export const POST_GET_REQUEST = "POST_GET_REQUEST";
export const POST_GET_SUCCESS = "POST_GET_SUCCESS";
export const POST_GET_FAIL = "POST_GET_FAIL";

// update post
export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAIL = "POST_UPDATE_FAIL";
export const UPDATE_POST_LIKES = "UPDATE_POST_LIKES";
export const UPDATE_RETWEET_COUNT = "UPDATE_RETWEET_COUNT";
export const DELETE_POST = "DELETE_POST";
// Add a comment to a post
export const POST_ADD_COMMENT_REQUEST = "POST_ADD_COMMENT_REQUEST";
export const POST_ADD_COMMENT_SUCCESS = "POST_ADD_COMMENT_SUCCESS";
export const POST_ADD_COMMENT_FAIL = "POST_ADD_COMMENT_FAIL";


// selected post
export const GET_SELECTED_POST_REQUEST = "GET_SELECTED_POST_REQUEST";
export const GET_SELECTED_POST = "GET_SELECTED_POST";
export const CLEAR_SELECTED_POST = "CLEAR_SELECTED_POST";
